name-template: "v$RESOLVED_VERSION"
tag-template: "v$RESOLVED_VERSION"

categories:
  - title: "Breaking Changes"
    labels:
      - "version:major"
  - title: "Features"
    labels:
      - "version:minor"
  - title: "Bug Fixes"
    labels:
      - "version:patch"
  - title: "Documentation"
    labels:
      - "type:docs"
  - title: "Build & CI"
    labels:
      - "type:build-definition"

version-resolver:
  major:
    labels:
      - "version:major"
  minor:
    labels:
      - "version:minor"
  patch:
    labels:
      - "version:patch"
  default: patch

template: |
  ## Changes

  $CHANGES

  **Full Changelog**: https://github.com/$OWNER/$REPOSITORY/compare/$PREVIOUS_TAG...v$RESOLVED_VERSION
