package sync

import (
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

// ---------------------------------------------------------------------------
// ComposeOverlays tests (T015)
// ---------------------------------------------------------------------------

func TestComposeOverlays_SingleFile(t *testing.T) {
	dir := t.TempDir()
	writeFile(t, filepath.Join(dir, "base.md"), "# Base Instructions\n\nBe helpful.\n")

	result, err := ComposeOverlays(dir, []string{"base.md"})
	require.NoError(t, err)
	require.NotNil(t, result)
	assert.Contains(t, string(result.Content), "# Base Instructions")
	assert.Contains(t, string(result.Content), "Be helpful.")
}

func TestComposeOverlays_MultipleFiles(t *testing.T) {
	dir := t.TempDir()
	writeFile(t, filepath.Join(dir, "base.md"), "Base content.\n")
	writeFile(t, filepath.Join(dir, "project.md"), "Project content.\n")

	result, err := ComposeOverlays(dir, []string{"base.md", "project.md"})
	require.NoError(t, err)

	content := string(result.Content)
	baseIdx := strings.Index(content, "Base content.")
	projIdx := strings.Index(content, "Project content.")
	assert.Greater(t, baseIdx, -1, "base content should be present")
	assert.Greater(t, projIdx, -1, "project content should be present")
	assert.True(t, baseIdx < projIdx, "base content should appear before project content")
}

func TestComposeOverlays_PrependsHeader(t *testing.T) {
	dir := t.TempDir()
	writeFile(t, filepath.Join(dir, "base.md"), "Content\n")

	result, err := ComposeOverlays(dir, []string{"base.md"})
	require.NoError(t, err)

	content := string(result.Content)
	assert.True(t, strings.HasPrefix(content, "<!-- DO NOT EDIT"), "should start with managed header")
	assert.Contains(t, content, "Generated by ailign")
	assert.Contains(t, content, "ailign sync")
}

func TestComposeOverlays_HeaderContainsSources(t *testing.T) {
	dir := t.TempDir()
	writeFile(t, filepath.Join(dir, "a.md"), "A\n")
	writeFile(t, filepath.Join(dir, "b.md"), "B\n")

	result, err := ComposeOverlays(dir, []string{"a.md", "b.md"})
	require.NoError(t, err)

	content := string(result.Content)
	assert.Contains(t, content, "a.md")
	assert.Contains(t, content, "b.md")
}

func TestComposeOverlays_PathTraversalRejected(t *testing.T) {
	dir := t.TempDir()

	_, err := ComposeOverlays(dir, []string{"../../etc/passwd"})
	require.Error(t, err)
	assert.Contains(t, err.Error(), "traversal")
}

func TestComposeOverlays_NonUTF8Rejected(t *testing.T) {
	dir := t.TempDir()
	// Write binary content (invalid UTF-8)
	require.NoError(t, os.WriteFile(filepath.Join(dir, "binary.md"), []byte{0xFF, 0xFE, 0x00, 0x01}, 0644))

	_, err := ComposeOverlays(dir, []string{"binary.md"})
	require.Error(t, err)
	assert.Contains(t, err.Error(), "UTF-8")
}

func TestComposeOverlays_EmptyFileWarning(t *testing.T) {
	dir := t.TempDir()
	writeFile(t, filepath.Join(dir, "empty.md"), "")

	result, err := ComposeOverlays(dir, []string{"empty.md"})
	require.NoError(t, err)
	require.NotEmpty(t, result.Warnings)
	assert.Contains(t, result.Warnings[0], "empty")
}

func TestComposeOverlays_MissingFile(t *testing.T) {
	dir := t.TempDir()

	_, err := ComposeOverlays(dir, []string{"nonexistent.md"})
	require.Error(t, err)
	assert.Contains(t, err.Error(), "not found")
}

// ---------------------------------------------------------------------------
// Test helper
// ---------------------------------------------------------------------------

func writeFile(t *testing.T, path string, content string) {
	t.Helper()
	dir := filepath.Dir(path)
	require.NoError(t, os.MkdirAll(dir, 0755))
	require.NoError(t, os.WriteFile(path, []byte(content), 0644))
}
