package sync

import (
	"errors"
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"unicode/utf8"
)

// ComposeOverlays reads and composes overlay files in order,
// prepending a managed-content header.
func ComposeOverlays(baseDir string, overlays []string) (*ComposeResult, error) {
	result := &ComposeResult{}
	var parts []string

	for _, overlay := range overlays {
		if err := validateOverlayPath(baseDir, overlay); err != nil {
			return nil, err
		}

		fullPath := filepath.Join(baseDir, overlay)
		data, err := os.ReadFile(fullPath)
		if err != nil {
			if errors.Is(err, os.ErrNotExist) {
				return nil, fmt.Errorf("overlay file not found: %s", overlay)
			}
			return nil, fmt.Errorf("reading overlay %s: %w", overlay, err)
		}

		if !utf8.Valid(data) {
			return nil, fmt.Errorf("overlay %s contains invalid UTF-8 content", overlay)
		}

		content := string(data)
		if len(strings.TrimSpace(content)) == 0 {
			result.Warnings = append(result.Warnings, fmt.Sprintf("overlay %s is empty", overlay))
		}

		parts = append(parts, content)
	}

	header := buildHeader(overlays)
	composed := header + strings.Join(parts, "\n")
	result.Content = []byte(composed)

	return result, nil
}

// validateOverlayPath checks that an overlay path doesn't escape the base directory.
func validateOverlayPath(baseDir, overlay string) error {
	cleaned := filepath.Clean(overlay)
	absPath := filepath.Join(baseDir, cleaned)

	// Ensure the resolved path stays within baseDir
	rel, err := filepath.Rel(baseDir, absPath)
	if err != nil {
		return fmt.Errorf("overlay path traversal rejected: %s", overlay)
	}
	if strings.HasPrefix(rel, "..") {
		return fmt.Errorf("overlay path traversal rejected: %s", overlay)
	}

	return nil
}

// buildHeader creates the managed-content header for the hub file.
func buildHeader(sources []string) string {
	return fmt.Sprintf("<!-- DO NOT EDIT — Generated by ailign\n   Source: %s\n   Regenerate: ailign sync\n-->\n\n",
		strings.Join(sources, ", "))
}
