@wip
# Source: specs/002-local-instruction-sync/spec.md - User Story 1

Feature: Sync Local Instructions to Target Files
  In order to maintain consistent AI instructions across multiple tools
  As a developer working in a repository
  I want to sync my local instruction files to all configured target
  formats with a single command

  Background:
    Given a repository with a valid .ailign.yml

  Scenario: Sync single overlay to multiple targets
    Given a .ailign.yml with targets "claude,cursor" and overlay "base.md"
    And an overlay file "base.md" containing "Use TypeScript strict mode"
    When the developer runs ailign sync
    Then the hub file ".ailign/instructions.md" will be written
    And symlinks will be created at ".claude/instructions.md,.cursorrules"
    And each target file will contain "Use TypeScript strict mode"
    And it will exit with code 0

  Scenario: Sync multiple overlays composed in order
    Given a .ailign.yml with targets "claude" and overlays "base.md,project.md"
    And an overlay file "base.md" containing "Base instructions"
    And an overlay file "project.md" containing "Project context"
    When the developer runs ailign sync
    Then the target file ".claude/instructions.md" will contain "Base instructions" before "Project context"

  Scenario: Missing overlay file produces error
    Given a .ailign.yml with targets "claude" and overlay "missing.md"
    And the overlay file "missing.md" does not exist
    When the developer runs ailign sync
    Then it will report an error containing "missing.md" to stderr
    And it will report an error containing "not found" to stderr
    And the hub file ".ailign/instructions.md" will not exist
    And it will exit with code 2

  Scenario: Target directory created if missing
    Given a .ailign.yml with targets "claude" and overlay "base.md"
    And an overlay file "base.md" containing "Instructions"
    And the directory ".claude" does not exist
    When the developer runs ailign sync
    Then the directory ".claude" will be created
    And a symlink will exist at ".claude/instructions.md"

  Scenario: Output files include managed-content header
    Given a .ailign.yml with targets "cursor" and overlay "base.md"
    And an overlay file "base.md" containing "Instructions"
    When the developer runs ailign sync
    Then the target file ".cursorrules" will start with "<!-- DO NOT EDIT"
    And the target file ".cursorrules" will contain "Generated by ailign"
    And the target file ".cursorrules" will contain "base.md"

  Scenario: No local_overlays configured
    Given a .ailign.yml with targets "claude" and no local_overlays
    When the developer runs ailign sync
    Then it will report an error containing "no local_overlays configured" to stderr
    And it will exit with code 2

  Scenario: Existing target file is replaced with symlink
    Given a .ailign.yml with targets "cursor" and overlay "base.md"
    And an overlay file "base.md" containing "New instructions"
    And a regular file exists at ".cursorrules" containing "Old content"
    When the developer runs ailign sync
    Then ".cursorrules" will be a symlink
    And the target file ".cursorrules" will contain "New instructions"

  Scenario: Subsequent sync updates hub content without recreating symlinks
    Given a .ailign.yml with targets "cursor" and overlay "base.md"
    And an overlay file "base.md" containing "Version 1"
    And ailign sync has been run previously
    When the overlay file "base.md" is changed to "Version 2"
    And the developer runs ailign sync
    Then the target file ".cursorrules" will contain "Version 2"
    And ".cursorrules" will be a symlink

  Scenario: Sync results reported to stdout
    Given a .ailign.yml with targets "claude,cursor" and overlay "base.md"
    And an overlay file "base.md" containing "Instructions"
    When the developer runs ailign sync
    Then stdout will contain "claude"
    And stdout will contain "cursor"
    And stdout will contain "Synced"

  Scenario: Sync results in JSON format
    Given a .ailign.yml with targets "claude" and overlay "base.md"
    And an overlay file "base.md" containing "Instructions"
    When the developer runs ailign sync with "--format json"
    Then stdout will be valid JSON
    And the JSON output will contain target "claude" with status "created"

  @edge-case
  Scenario: Empty overlay file produces warning
    Given a .ailign.yml with targets "claude" and overlay "empty.md"
    And an overlay file "empty.md" that is empty
    When the developer runs ailign sync
    Then it will report a warning containing "empty.md" to stderr
    And the hub file ".ailign/instructions.md" will be written
    And it will exit with code 0

  @edge-case
  Scenario: Overlay path traversal rejected
    Given a .ailign.yml with targets "claude" and overlay "../../secrets/instructions.md"
    When the developer runs ailign sync
    Then it will report an error containing "escapes repository root" to stderr
    And it will exit with code 2

  @edge-case
  Scenario: Non-UTF-8 overlay content rejected
    Given a .ailign.yml with targets "claude" and overlay "binary.md"
    And an overlay file "binary.md" containing non-UTF-8 bytes
    When the developer runs ailign sync
    Then it will report an error containing "encoding" to stderr
    And it will exit with code 2

  @edge-case
  Scenario: Read-only target directory produces error
    Given a .ailign.yml with targets "cursor" and overlay "base.md"
    And an overlay file "base.md" containing "Instructions"
    And the target file ".cursorrules" is not writable
    When the developer runs ailign sync
    Then it will report an error containing "permission" to stderr
    And it will exit with code 2
