@wip
# Source: specs/002-local-instruction-sync/spec.md - User Story 1

Feature: Sync Local Instructions to Target Files
  In order to maintain consistent AI instructions across multiple tools
  As a developer working in a repository
  I want to sync my local instruction files to all configured target
  formats with a single command

  Background:
    Given a repository with a valid .ailign.yml

  Scenario: Sync single overlay to multiple targets
    Given a .ailign.yml with targets "claude,cursor" and overlay "base.md"
    And an overlay file "base.md" containing "Use TypeScript strict mode"
    When the developer runs ailign sync
    Then the hub file ".ailign/instructions.md" is written
    And symlinks are created at ".claude/instructions.md,.cursorrules"
    And each target file contains "Use TypeScript strict mode"
    And it exits with code 0

  Scenario: Sync multiple overlays composed in order
    Given a .ailign.yml with targets "claude" and overlays "base.md,project.md"
    And an overlay file "base.md" containing "Base instructions"
    And an overlay file "project.md" containing "Project context"
    When the developer runs ailign sync
    Then the target file ".claude/instructions.md" contains "Base instructions" before "Project context"

  Scenario: Missing overlay file produces error
    Given a .ailign.yml with targets "claude" and overlay "missing.md"
    And the overlay file "missing.md" does not exist
    When the developer runs ailign sync
    Then it reports an error containing "missing.md" to stderr
    And it reports an error containing "not found" to stderr
    And the hub file ".ailign/instructions.md" does not exist
    And it exits with code 2

  Scenario: Target directory created if missing
    Given a .ailign.yml with targets "claude" and overlay "base.md"
    And an overlay file "base.md" containing "Instructions"
    And the directory ".claude" does not exist
    When the developer runs ailign sync
    Then the directory ".claude" is created
    And a symlink exists at ".claude/instructions.md"

  Scenario: Output files include managed-content header
    Given a .ailign.yml with targets "cursor" and overlay "base.md"
    And an overlay file "base.md" containing "Instructions"
    When the developer runs ailign sync
    Then the target file ".cursorrules" starts with "<!-- DO NOT EDIT"
    And the target file ".cursorrules" contains "Generated by ailign"
    And the target file ".cursorrules" contains "base.md"

  Scenario: No local_overlays configured
    Given a .ailign.yml with targets "claude" and no local_overlays
    When the developer runs ailign sync
    Then it reports an error containing "no local_overlays configured" to stderr
    And it exits with code 2

  Scenario: Existing target file is replaced with symlink
    Given a .ailign.yml with targets "cursor" and overlay "base.md"
    And an overlay file "base.md" containing "New instructions"
    And a regular file exists at ".cursorrules" containing "Old content"
    When the developer runs ailign sync
    Then ".cursorrules" is a symlink
    And the target file ".cursorrules" contains "New instructions"

  Scenario: Subsequent sync updates hub content without recreating symlinks
    Given a .ailign.yml with targets "cursor" and overlay "base.md"
    And an overlay file "base.md" containing "Version 1"
    And ailign sync has been run previously
    When the overlay file "base.md" is changed to "Version 2"
    And the developer runs ailign sync
    Then the target file ".cursorrules" contains "Version 2"
    And ".cursorrules" is a symlink

  Scenario: Sync results reported to stdout
    Given a .ailign.yml with targets "claude,cursor" and overlay "base.md"
    And an overlay file "base.md" containing "Instructions"
    When the developer runs ailign sync
    Then stdout contains "claude"
    And stdout contains "cursor"
    And stdout contains "Synced"

  Scenario: Sync results in JSON format
    Given a .ailign.yml with targets "claude" and overlay "base.md"
    And an overlay file "base.md" containing "Instructions"
    When the developer runs ailign sync with "--format json"
    Then stdout is valid JSON
    And the JSON output contains target "claude" with status "created"

  @edge-case
  Scenario: Empty overlay file produces warning
    Given a .ailign.yml with targets "claude" and overlay "empty.md"
    And an overlay file "empty.md" that is empty
    When the developer runs ailign sync
    Then it reports a warning containing "empty.md" to stderr
    And the hub file ".ailign/instructions.md" is written
    And it exits with code 0

  @edge-case
  Scenario: Overlay path traversal rejected
    Given a .ailign.yml with targets "claude" and overlay "../../secrets/instructions.md"
    When the developer runs ailign sync
    Then it reports an error containing "escapes repository root" to stderr
    And it exits with code 2

  @edge-case
  Scenario: Non-UTF-8 overlay content rejected
    Given a .ailign.yml with targets "claude" and overlay "binary.md"
    And an overlay file "binary.md" containing non-UTF-8 bytes
    When the developer runs ailign sync
    Then it reports an error containing "encoding" to stderr
    And it exits with code 2

  @edge-case
  Scenario: Read-only target directory produces error
    Given a .ailign.yml with targets "cursor" and overlay "base.md"
    And an overlay file "base.md" containing "Instructions"
    And the target file ".cursorrules" is not writable
    When the developer runs ailign sync
    Then it reports an error containing "permission" to stderr
    And it exits with code 2
